import json
import os
import stat
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import Literal

from typing_extensions import TypedDict

from app.constants import DATA_DIR
from app.utils.HostPath import DOCKER_HOST_ROOT, ToHostPath, ToRuntimePath


class KonomiTVBS4KRecordingBindDocument(TypedDict):
    services: dict[str, KonomiTVBS4KRecordingBindService]


class KonomiTVBS4KRecordingBindService(TypedDict):
    volumes: list[KonomiTVBS4KRecordingBind]


class KonomiTVBS4KRecordingBind(TypedDict):
    type: Literal['bind']
    source: str
    target: str
    read_only: Literal[True]
    bind: KonomiTVBS4KRecordingBindOptions


class KonomiTVBS4KRecordingBindOptions(TypedDict):
    create_host_path: Literal[False]


class KonomiTVBS4KRecordingBindResult(TypedDict):
    recording_bind_count: int


def GenerateKonomiTVBS4KRecordingBinds(recorded_folders: Sequence[Path]) -> int:
    """録画フォルダの設定から、非公開のCompose継承用ファイルを生成する。

    Args:
        recorded_folders: 通常のサーバー設定読込みで取得した録画フォルダ群。
    Returns:
        重複を除いた共有ディレクトリ数。実ホストパスは標準出力へ出さない。
    """
    volumes: list[KonomiTVBS4KRecordingBind] = []
    seen: set[Path] = set()
    # 全件検証してから出力する。失敗時に既存の共有定義を部分的に置換しない。
    for folder in recorded_folders:
        runtime = ToRuntimePath(folder).resolve(strict=True)
        if runtime == DOCKER_HOST_ROOT or not runtime.is_relative_to(DOCKER_HOST_ROOT):
            raise ValueError('Recording folders must resolve within the Docker host view, not to its root.')
        if not runtime.is_dir() or not os.access(runtime, os.R_OK | os.X_OK):
            raise ValueError('Recording folder is not readable.')
        home = Path('/host-home')
        if home.exists() and runtime.samefile(home):
            raise ValueError('Sharing the entire host home is not allowed.')
        if runtime in seen:
            continue
        seen.add(runtime)
        # Composeの変数展開で、ファイル名に含まれる$を別のパスへ変えてしまわない。
        # 外部の録画領域をSELinux relabelしない。元データの属性にも触れない。
        volumes.append(KonomiTVBS4KRecordingBind(
            type='bind', source=str(ToHostPath(runtime)).replace('$', '$$'),
            target=str(runtime).replace('$', '$$'), read_only=True,
            bind=KonomiTVBS4KRecordingBindOptions(create_host_path=False),
        ))
    document = KonomiTVBS4KRecordingBindDocument(services={
        'konomitv-bs4k-recording-inputs': KonomiTVBS4KRecordingBindService(volumes=volumes),
    })
    marker = '# Generated by KonomiTVBS4KRecordingBinds.\n'
    output = DATA_DIR / 'konomitv-bs4k-recording-binds.yaml'
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    if output.is_symlink():
        raise ValueError('Refusing a symlink for generated recording binds.')
    if output.exists():
        existing_fd = os.open(output, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
        with os.fdopen(existing_fd, encoding='utf-8') as existing:
            if not stat.S_ISREG(os.fstat(existing.fileno()).st_mode):
                raise ValueError('Generated recording binds must be a regular file.')
            if existing.readline(len(marker) + 1) != marker:
                raise ValueError('Refusing to overwrite an unmanaged file.')
    fd, temporary = tempfile.mkstemp(prefix='.recording-binds-', dir=DATA_DIR)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as handle:
            handle.write(marker)
            # JSONはYAMLの部分集合。パス文字列を手書きのYAMLへ補間しない。
            json.dump(document, handle, ensure_ascii=True, indent=2)
            handle.write('\n')
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, output)
        directory_fd = os.open(DATA_DIR, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        Path(temporary).unlink(missing_ok=True)
    return len(volumes)


if __name__ == '__main__':
    from app.config import LoadConfig

    settings = LoadConfig(bypass_validation=True)
    print(json.dumps(KonomiTVBS4KRecordingBindResult(
        recording_bind_count=GenerateKonomiTVBS4KRecordingBinds(settings.video.recorded_folders),
    )))
