name: Publish Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.message, 'Release:')
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo version=$(echo "$COMMIT_MESSAGE" | sed -e 's/Release: version //') >> $GITHUB_OUTPUT

      - name: Create New Version Tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag v${{ steps.get_version.outputs.version }} ${{ github.sha }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create Release Without Assets
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: KonomiTV-BS4K ${{ steps.get_version.outputs.version }}
          tag: v${{ steps.get_version.outputs.version }}
